version: '3'
volumes:
  bot_data:
services:
  menu_bot:
    image: date_bot
    container_name: date_bot_container
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - bot_data:/app/database/data
    restart: always